server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://192.168.78.101:5432/ArquiEjem?useSSL=false
    username: postgres
    password: 13643389
    driver-class-name: org.postgresql.Driver